### ISSUE TITLE
Observations for migrating to Nim v2.0

### ISSUE THREAD

**Issue by samsamros** [mashingan/anonimongo#21]
So, I've been using this for a while, and love the code and the ease to use it. I've recently started trying my code on Nim v2.0 and got a bunch of errors. I managed to take out some, but I don't know if I'm messing up stuff that will break the world! :(

### Error 1: 
```
/home/localhost/.choosenim/toolchains/nim-2.0.0/lib/pure/strutils.nim(1855, 6) Error: 'join' can have side effects
> /home/localhost/.choosenim/toolchains/nim-2.0.0/lib/pure/strutils.nim(1865, 17) Hint: 'join' calls `.sideEffect` '$'
>> /home/localhost/.nimble/pkgs/anonimongo-0.6.3/anonimongo/core/bson.nim(599, 6) Hint: '$' called by 'join'
```
went to line 1855 of strutils and changed func to proc, that did it. no error, after.

### Error 2:
```
/home/localhost/.nimble/pkgs/scram-0.2.0/scram/private/utils.nim(32, 20) Error: undeclared identifier: 'PEVP_MD'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (2, 3): 'EVP_MD'
```
Just as spellSuggest suggests I changed PEVP_MD to EVP_MD in scram utils file. Lines 32,33,35 and 170.

Seems to be compiling fine now. 

### Error 3:

I traced back with the {.gcsafe.} pragma all the way to this function:
```
proc pickAnyServer*[T: MultiSock](m: Mongo[T], test: (string, int) -> bool = nil): MongoConn[T] {.gcsafe.} =
  var res: MongoConn[T]
  for host{.inject.}, server{.inject.} in m.servers:
    #if `test`:
    if test == nil or (test != nil and test(host, server.pool.available.len)):
      res = server
  res
```
Line 452 in core/types. After adding the pragma there, too, I got this error from the compiler:

```
/home/localhost/.nimble/pkgs/anonimongo-0.6.3/anonimongo/core/types.nim(452, 6) Error: 'pickAnyServer' is not GC-safe as it performs an indirect call via 'test'
```
I  tried removing the test(host, server.pool.available.len), and did compile... but I'm not sure if this will bring new issues, or if the proc is defined somewhere else I couldn't tell. I looked for it with grep on the whole anonimongo codebase, and could not spot it. I tried defining it as a type, which didn't help either. Calling it without prior definition seems to be an issue (which didn't come up before). I've been compiling it fine since 1.4

### Error 4: 
```
/home/localhost/.nimble/pkgs/scram-0.2.0/scram/client.nim(75, 59) Error: type mismatch
Expression: encode(clientProof, newLine = "")
  [1] clientProof: SHA256Digest
  [2] newLine = "": newLine: string

Expected one of (first mismatch at [position]):
[1] proc encode[T: SomeInteger and not byte](s: openArray[T]; safe = false): string
[2] proc encode[T: byte | char](s: openArray[T]; safe = false): string
```
For this I just reviewed base64's encode function:
```
proc encode*[T: SomeInteger|char](s: openArray[T], safe = false): string =
...
```
I removed newLine = ""
```
clientFinalMessageWithoutProof & ",p=" & base64.encode(clientProof, newLine="")
```

Finally, everything compiled, and I'm testing it... so far, so good!

----

I really appreciate your hard work (this is great code), and I had some other questions I may ask later on about the aggregation cursor, and see if there's a way to make that iterate. but I'll leave that for a separate issue.

**Comment by mashingan** [comment]
Thank you for experiment of migrating to Nim v2. I haven't had any chance to test migrating it myself due to time constraint.

Let me comment several errors observed here:

> Error 1:

This error is (likely) harmless. It couldn't be compiled due to changes from `proc` to `func`. As you fixed, by changing it back to `proc`, it worked normally.
However this is from standard library `std/strutils`. While this seems trivial I'd like to wait and see first about this change.

> Error 2:

This error is in dependency module and can't understand why the symbol is different and to what effect it's changed. Cannot say much except watching whether it's solved in newer scram module version.

> Error 3:

Previously the `pickAnyServer` was a template. I can't remember why changed it to proc. Removing the calling `test` would likely break the `readPreferences`, I'd say it'll break all mode (except `ReadPreference.primary`) but couldn't be sure yet because I haven't ran the test.

> Error 4:

This is again error in `scram` module. I think it's because the API change in `std/base64` module so `scram` needs to adapt to this change. As before, this likely be fixed in newer `scram` version.

---

Since it's harder for me to maintain/add new features to Anonimongo, I invited you for managing this library. Feel free to accept/reject it :)

**Comment by samsamros** [comment]
I appreciate the invite! I'll do my best... I really like this library and I think it's the most developed, maintained and documented! So, I will study the code more meticulously to provide better ideas!

Now, I think I'll leave the scram and standard lib code as is, and will continue playing around with the proc that used to be a template. I was wondering why there were {.inject.} pragmas in the proc, but maybe I can explore leaving it as a template and see what happens. Maybe I'll run into the same issue as you did when you initially changed it to a proc. I will explore a bit more, and monitor scram's updates.

I'll open some new issues for some other features I was thinking about, and bounce them around here!

**Comment by mashingan** [comment]
I did look the commit on why it's changed from template to proc. Apparently the template couldn't support the generic (starting from version 0.6.0 I added for both modes, sync with net.Socket and async with asyncdispatch.AsyncSocket) so I had to change it to proc for supplying the generic symbol. I reverted it back to template but couldn't test intensively so could you apply this patch and test it? 
[types.nim.zip](https://github.com/mashingan/anonimongo/files/12267891/types.nim.zip).
If this is seemed fine, you can create a PR and merge it immediately :)
As for the inject pragma, I think I just forgot to remove it from template before.

If you have other features in mind and perhaps implemented some of it, feel free to immediately merge to branch develop :)
Don't worry about breaking it :D, we have versioning with tag so it's fine to break it often to understand the existing codes.

---
On some unrelated notes, I'm trying to fix the test for replication in Mongo 6. On Windows, it worked fine (I migrated to Linux so cannot confirm it anymore) but on Linux (specifically Ubuntu), it hangs indefinitely after setting up replication.
There were attempts to run Mongo 6 in Github Action, before I rolled it back to Mongo 4.4 due to this behavior.
This is the reason why I can't migrate this to Nim v2 for the time being.

**Comment by samsamros** [comment]
I'm reverting to 1.6.14 to test the patch with a few programs! :)

will let you know!

I'm on mongo 6, both aarch64 for raspberry pi, and amd64. I haven't tested replicas though!
Everything else seems to work alright. But if you've detected other issues on mongo 6, I can switch to 4.4 for testing the patch.

**Comment by samsamros** [comment]
Just wanted to report back. I've been testing one project and has worked well with the patch. This application only finds users in a database and does not perform any advanced things. Bson to Json, that's all. I wanted to test it first with simple applications and then move on onto more advanced uses. 
Some observations on this application:
1) uses authentication (SHA256Digest)
2) works with threads on
3) works with orc as gc

I will move to an application that uses aggregation, finds, and other features.

**Comment by mashingan** [comment]
Thank you very much for testing thoroughly. Feel free to apply the patch and bump versions up if you feel you've tested enough :+1:

**Comment by inv2004** [comment]
@samsamros 
Thank you for raising it. I think that mongo lib is pretty critical for any language. I would say that language is not exists if it does not have even mongo driver :)

I decided to fix it and you can my my PR here https://github.com/mashingan/anonimongo/pull/24

Let me describe it:
1) `$` - I did not expect Nim is so clever on effects. Join is really changed to `func` (I am not 100% that it is right change in nim, because we still use `$` but redefined in with proc), but we have to follow it for the moment. The problem that a some of `$` from some bson structs creates side-effects. I just defined the same for BsonArray, which is pretty similar to that `json` do

2) It is about scram dep: PEVP_MD => EVP_MD seems correct, I checked ssl manual and looks like mentioned functions return EVP_MD => looks like correct

3) Haven't hit the error locally

4) Looks like it is very legacy code - I just removed the very old nim version support (which understands the newLine)

I am able to build it, but was not able to complete nimble test
